FROM debian:bullseye
RUN apt-get update && apt-get upgrade -y
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    apt-get update -y && \
    apt-get install gcc mono-mcs -y && \
    apt-get install wget -y $$ \
    wget https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.7-linux-amd64.tar.gz && \
    tar xzf influxdb2-2.0.7-linux-amd64.tar.gz && \
    cp influxdb2-2.0.7-linux-amd64/influx* /usr/local/bin/ && \
    influxd version && \
    influx version
